// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.2
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NoteAPI_GetNote_FullMethodName                  = "/api.notes.v1.NoteAPI/GetNote"
	NoteAPI_CreateNote_FullMethodName               = "/api.notes.v1.NoteAPI/CreateNote"
	NoteAPI_StreamNotes_FullMethodName              = "/api.notes.v1.NoteAPI/StreamNotes"
	NoteAPI_StreamNotesBidirectional_FullMethodName = "/api.notes.v1.NoteAPI/StreamNotesBidirectional"
)

// NoteAPIClient is the client API for NoteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteAPIClient interface {
	GetNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*NoteResponse, error)
	CreateNote(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*NoteCreateResponse, error)
	StreamNotes(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (NoteAPI_StreamNotesClient, error)
	StreamNotesBidirectional(ctx context.Context, opts ...grpc.CallOption) (NoteAPI_StreamNotesBidirectionalClient, error)
}

type noteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteAPIClient(cc grpc.ClientConnInterface) NoteAPIClient {
	return &noteAPIClient{cc}
}

func (c *noteAPIClient) GetNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*NoteResponse, error) {
	out := new(NoteResponse)
	err := c.cc.Invoke(ctx, NoteAPI_GetNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) CreateNote(ctx context.Context, in *NoteCreateRequest, opts ...grpc.CallOption) (*NoteCreateResponse, error) {
	out := new(NoteCreateResponse)
	err := c.cc.Invoke(ctx, NoteAPI_CreateNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *noteAPIClient) StreamNotes(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (NoteAPI_StreamNotesClient, error) {
	stream, err := c.cc.NewStream(ctx, &NoteAPI_ServiceDesc.Streams[0], NoteAPI_StreamNotes_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &noteAPIStreamNotesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type NoteAPI_StreamNotesClient interface {
	Recv() (*NoteResponse, error)
	grpc.ClientStream
}

type noteAPIStreamNotesClient struct {
	grpc.ClientStream
}

func (x *noteAPIStreamNotesClient) Recv() (*NoteResponse, error) {
	m := new(NoteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *noteAPIClient) StreamNotesBidirectional(ctx context.Context, opts ...grpc.CallOption) (NoteAPI_StreamNotesBidirectionalClient, error) {
	stream, err := c.cc.NewStream(ctx, &NoteAPI_ServiceDesc.Streams[1], NoteAPI_StreamNotesBidirectional_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &noteAPIStreamNotesBidirectionalClient{stream}
	return x, nil
}

type NoteAPI_StreamNotesBidirectionalClient interface {
	Send(*NoteRequest) error
	Recv() (*NoteResponse, error)
	grpc.ClientStream
}

type noteAPIStreamNotesBidirectionalClient struct {
	grpc.ClientStream
}

func (x *noteAPIStreamNotesBidirectionalClient) Send(m *NoteRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *noteAPIStreamNotesBidirectionalClient) Recv() (*NoteResponse, error) {
	m := new(NoteResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NoteAPIServer is the server API for NoteAPI service.
// All implementations should embed UnimplementedNoteAPIServer
// for forward compatibility
type NoteAPIServer interface {
	GetNote(context.Context, *NoteRequest) (*NoteResponse, error)
	CreateNote(context.Context, *NoteCreateRequest) (*NoteCreateResponse, error)
	StreamNotes(*NoteRequest, NoteAPI_StreamNotesServer) error
	StreamNotesBidirectional(NoteAPI_StreamNotesBidirectionalServer) error
}

// UnimplementedNoteAPIServer should be embedded to have forward compatible implementations.
type UnimplementedNoteAPIServer struct {
}

func (UnimplementedNoteAPIServer) GetNote(context.Context, *NoteRequest) (*NoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}
func (UnimplementedNoteAPIServer) CreateNote(context.Context, *NoteCreateRequest) (*NoteCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNote not implemented")
}
func (UnimplementedNoteAPIServer) StreamNotes(*NoteRequest, NoteAPI_StreamNotesServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNotes not implemented")
}
func (UnimplementedNoteAPIServer) StreamNotesBidirectional(NoteAPI_StreamNotesBidirectionalServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamNotesBidirectional not implemented")
}

// UnsafeNoteAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteAPIServer will
// result in compilation errors.
type UnsafeNoteAPIServer interface {
	mustEmbedUnimplementedNoteAPIServer()
}

func RegisterNoteAPIServer(s grpc.ServiceRegistrar, srv NoteAPIServer) {
	s.RegisterService(&NoteAPI_ServiceDesc, srv)
}

func _NoteAPI_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetNote(ctx, req.(*NoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_CreateNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).CreateNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_CreateNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).CreateNote(ctx, req.(*NoteCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NoteAPI_StreamNotes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NoteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(NoteAPIServer).StreamNotes(m, &noteAPIStreamNotesServer{stream})
}

type NoteAPI_StreamNotesServer interface {
	Send(*NoteResponse) error
	grpc.ServerStream
}

type noteAPIStreamNotesServer struct {
	grpc.ServerStream
}

func (x *noteAPIStreamNotesServer) Send(m *NoteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _NoteAPI_StreamNotesBidirectional_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NoteAPIServer).StreamNotesBidirectional(&noteAPIStreamNotesBidirectionalServer{stream})
}

type NoteAPI_StreamNotesBidirectionalServer interface {
	Send(*NoteResponse) error
	Recv() (*NoteRequest, error)
	grpc.ServerStream
}

type noteAPIStreamNotesBidirectionalServer struct {
	grpc.ServerStream
}

func (x *noteAPIStreamNotesBidirectionalServer) Send(m *NoteResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *noteAPIStreamNotesBidirectionalServer) Recv() (*NoteRequest, error) {
	m := new(NoteRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// NoteAPI_ServiceDesc is the grpc.ServiceDesc for NoteAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NoteAPI",
	HandlerType: (*NoteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _NoteAPI_GetNote_Handler,
		},
		{
			MethodName: "CreateNote",
			Handler:    _NoteAPI_CreateNote_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamNotes",
			Handler:       _NoteAPI_StreamNotes_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamNotesBidirectional",
			Handler:       _NoteAPI_StreamNotesBidirectional_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/notes/v1/notes.proto",
}
