// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.28.2
// source: api/notes/v1/notes.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	NoteAPI_GetNote_FullMethodName = "/api.notes.v1.NoteAPI/GetNote"
)

// NoteAPIClient is the client API for NoteAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NoteAPIClient interface {
	GetNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*NoteResponse, error)
}

type noteAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewNoteAPIClient(cc grpc.ClientConnInterface) NoteAPIClient {
	return &noteAPIClient{cc}
}

func (c *noteAPIClient) GetNote(ctx context.Context, in *NoteRequest, opts ...grpc.CallOption) (*NoteResponse, error) {
	out := new(NoteResponse)
	err := c.cc.Invoke(ctx, NoteAPI_GetNote_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NoteAPIServer is the server API for NoteAPI service.
// All implementations should embed UnimplementedNoteAPIServer
// for forward compatibility
type NoteAPIServer interface {
	GetNote(context.Context, *NoteRequest) (*NoteResponse, error)
}

// UnimplementedNoteAPIServer should be embedded to have forward compatible implementations.
type UnimplementedNoteAPIServer struct {
}

func (UnimplementedNoteAPIServer) GetNote(context.Context, *NoteRequest) (*NoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNote not implemented")
}

// UnsafeNoteAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NoteAPIServer will
// result in compilation errors.
type UnsafeNoteAPIServer interface {
	mustEmbedUnimplementedNoteAPIServer()
}

func RegisterNoteAPIServer(s grpc.ServiceRegistrar, srv NoteAPIServer) {
	s.RegisterService(&NoteAPI_ServiceDesc, srv)
}

func _NoteAPI_GetNote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NoteAPIServer).GetNote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: NoteAPI_GetNote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NoteAPIServer).GetNote(ctx, req.(*NoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NoteAPI_ServiceDesc is the grpc.ServiceDesc for NoteAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NoteAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.notes.v1.NoteAPI",
	HandlerType: (*NoteAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetNote",
			Handler:    _NoteAPI_GetNote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/notes/v1/notes.proto",
}
